### ISSUE TITLE
%+% should allow changing data

### ISSUE THREAD

**Issue by malcook** [RGLab/ggcyto#2]
Hi.

In ggplot, 'adding' a dataframe to a plot with '%+%' serves to change the data underlying the plot.

Could this be made to work as well with flowSet/flowFrame and friends?

**Comment by mikejiang** [comment]
The idea of `%+%` operator for `data.frame` in `ggplot` is to switch to new data without re-typing of the previous `ggplot` constructor and all the layers. 
However, in `ggcyto`, a great deal of  preprocessing jobs are done during these very initial plot building steps (i.e `ggcyto` constructor and its overloaded `+` operator)
These preprocessing steps are pretty data-denpendent, e.g.fuzzy-lookup for the partial `marker` or `channel` names, extracting `gates` and `stats` from the data for `geom_gate` and `geom_stats` layers, etc...).

 One way of implementing this is to store all the initial constuctor and layers somewhere before preprocessing them and then repeat the same process behind the scene once `%+%` is invoked. 

But we will have to think more about this since it won't be as simple as replacing the underlying `data.frame` like `ggplot` does.

**Comment by malcook** [comment]
Understood - thanks for considering my request.  It really is quite useful
syntactic sugar.

**Comment by mikejiang** [comment]
@malcook , feel free to try it out
