### ISSUE TITLE
plotting derived values

### ISSUE THREAD

**Issue by malcook** [RGLab/ggcyto#3]
It seems it is not possible to plot derived values using ggcyto aesthetics

``` R
ggcyto(fs,aes(y= `PerCP.A` / `PE.A`,x=`PE.A`)) +
geom_hex(bins=64)+
scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
annotation_logticks()+                # Default: log ticks on bottom and left
facet_grid( Protein * Domain ~ Mutated ) + 
ggtitle('liveSubset')
```

Am I missing something?

My workaround now is to add derived columns using fsApply and cbind2:

fs<= fsApply(fs,function(ff) cbind2(ff,with(as.data.frame(ff@exprs),{ SOME EXPRESSION RETURNING A MATRIX})))

And I now see also I can use `transform` to similar effect.

But is there a better way?

Thanks!

**Comment by mikejiang** [comment]
Currently we don't support `derived` variable in `aes` at `ggcyto` level. The better workaround is to use `ggplot` directly on `flowSet`, e.g.
```r
ggplot(fs,aes(y= `PerCP.A` / `PE.A`,x=`PE.A`))
```
Some layers (e.g  `facet` and `scale_color_gradientn` ) must be added by user at `ggplot` level (they were added automatically by `ggcyto` wrapper )

Since you were already having customized `facet_grid`, you then only need to take care of `gradientn`, which can be retrieved from `hex_fill` element of `ggcyto_par_default()`. (i.e. `+ ggcyto_par_default()[["hex_fill"]]`)

see [here] for more examples of operating `flowSet` at `ggplot` level, (https://github.com/RGLab/ggcyto/blob/master/vignettes/ggplot.flowSet.2d.md)
