### ISSUE TITLE
geom_stats positioning beyond 'adjust'?

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/ggcyto#59]
I am adding gate labels (gate name and percent) to plots with quad gates. Is it possible to move the gate labels into the outside corners of each quadrant? The adjust parameter makes it difficult to position the labels in Q1 and Q3. 

![Rplot](https://user-images.githubusercontent.com/57542158/73795235-fe780d80-475e-11ea-9925-1ebd9baceb72.png)

**Comment by jacobpwagner** [comment]
How are you adding your labels? Can you give a code snippet?

**Comment by alexheubeck** [comment]
Here is the line for that plot:

CD8NaivevMemory <- ggcyto(gs[[1]], aes(x = CD197, y = CD45RA), subset = "CD8 T Cells", filter = marginalFilter) + geom_hex(bins=300) + ggcyto_par_set(limits = list(x = c(0,2.5), y = c(0,3))) + geom_gate(c('EM CD8 T Cells','CM CD8 T Cells','TEMRA CD8 T Cells','Naive CD8 T Cells') ,col='black') + **geom_stats('EM CD8 T Cells',type = c("gate_name", "percent"), adjust=0.2) + geom_stats('CM CD8 T Cells',type = c("gate_name", "percent"), adjust=0.35) + geom_stats('TEMRA CD8 T Cells',type = c("gate_name", "percent"), adjust=0.9) + geom_stats('Naive CD8 T Cells',type = c("gate_name", "percent"), adjust=0.8)** + axis_x_inverse_trans() + axis_y_inverse_trans() + theme_bw() + scale_fill_gradientn(colours = matlab.like2(300), trans = "sqrt")

**Comment by alexheubeck** [comment]
That works, I tried it before and got back an error, but it must have been unrelated. Thanks again for your help!

**Comment by jacobpwagner** [comment]
No problem. It will give a warning but it's innocuous and I'm working on getting rid of it.

This is mainly for my own tracking: 
The warning comes about because of the "density" column appended here:
https://github.com/RGLab/ggcyto/blob/c0596f5c2019980b31fa06fee6a94b84e6142072/R/ggcyto.R#L290-L294
which then means there are 3 columns here to multiply by instead of 2:
https://github.com/RGLab/ggcyto/blob/c0596f5c2019980b31fa06fee6a94b84e6142072/R/stat_position.R#L101

It still does the logically correct thing because it element-wise multiplies the first 2 by the first 2, but that's sloppy and should be fixed to remove the warning.

**Comment by jacobpwagner** [comment]
I'm actually re-opening this to remind myself to fix this when I get a chance.
