### ISSUE TITLE
Error: object 'update_theme' not found

### ISSUE THREAD

**Issue by marcelcosta** [RGLab/ggcyto#64]
Hi!

I'm using the package to plot some nodes from a gating set (imported from a flowJo workspace). When trying to use the "autoplot" or "ggcyto" function, I receive the following error message:

`Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'update_theme' not found`

After looking at the code of the "ggcyto_flowSet.R" function, at line 297 I've found:
`e1$theme <- ggplot2:::update_theme(e1$theme, e2)`

While at ggplot2 package (v. 3.3.0) there is no `update_theme` function but `theme_update`. I don't know if this is the problem or the two functions are not related.

Thank you!

**Comment by jacobpwagner** [comment]
This is due to a recent update in `ggplot2` and was already handled here: https://github.com/RGLab/ggcyto/commit/def48abcb85696e8c64c26d6e79040a30519cb04

That change should be made to the Bioconductor 3.10 release as well as the development version that will become Bioconductor 3.11. Have you installed/updated the package recently? If not, try reinstalling from Bioconductor and seeing if that solves the problem. Otherwise, you can also install from this GitHub repo directly.

**Comment by marcelcosta** [comment]
Thank you for the fast answer and I apologize posting an already addressed issue.

After updating Bioconductor and ggcyto packages correctly (I had tried before, but unsuccessfully), the function works fine.

Thanks!

**Comment by jacobpwagner** [comment]
No problem at all. Glad to hear it worked.
