### ISSUE TITLE
option to change and/or remove stats from autoplot

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [RGLab/ggcyto#66]
Hey guys,

Impressive work!

Do you think you could add an option in autoplot to turn off stats and/or change stats type ("percent", "count", "gate_name"). That would be really helpful for my own work!

I was thinking something along the lines of:
```
autoplot.GatingSet <- function(object, gate, x = NULL,  y = "SSC-A", bins = 30, axis_inverse_trans = TRUE, show.stats = TRUE, stats.type = "percent", ...){
.
.
.
p <- ggcyto(object, mapping, ...) + geom_hex(bins = bins) + geom_gate(gate)
if(show.stats){
    p <- p + geom_stats(type = stats.type) 
}
.
.
.
}
```

I'd appreciate your help!

**Comment by jacobpwagner** [comment]
Hi @PedroMilanezAlmeida . I understand it would be handy, but we are hesitant to add more options to `autoplot` as it's meant as a quick simple default plotting option. If we add more options it starts to lose that behavior and approach the more fine-tunable behavior that `ggcyto` (the method, not the package) already covers.

**Comment by SamGG** [comment]
Hi,
I think you could your own wrapper functions on top of ggcyto, if not already done.
Did you look at Dillon work in case it could simplify some of your work https://github.com/DillonHammill/CytoExploreR?
Best

**Comment by PedroMilanezAlmeida** [comment]
@jacobpwagner: I understand. What about adding only one single option, as in:

```
autoplot.GatingSet <- function(object, gate, x = NULL,  y = "SSC-A", bins = 30, axis_inverse_trans = TRUE, stats = "percent", ...){
.
.
.
p <- ggcyto(object, mapping, ...) + geom_hex(bins = bins) + geom_gate(gate)
if(stats != "none"){
    p <- p + geom_stats(type = stats) 
}
.
.
.
}
```
@SamGG: well, I wanted to avoid writing a wrapper since I am deploying the code as a plugin for FlowJo (github.com/pedromilanezalmeida/dafi and its sibling for batch analysis that is not ready yet). Btw, thanks for the link, I know about Dillon's work but hadnt realize it morphed into something so much bigger.

**Comment by mikejiang** [comment]
Maybe we could add `stats_null()` and `gate_null()` layers (similar to `facet_null`) to remove these default layers from `autoplot`?

**Comment by jacobpwagner** [comment]
I like that approach. Still allows for simple plotting with minimal arg specification and the same behavior as before, but easy removal of undesired layers. @PedroMilanezAlmeida , what do you think?

**Comment by PedroMilanezAlmeida** [comment]
That is ok. It won't allow changes to stats type though, right?

**Comment by mikejiang** [comment]
Maybe we should allow the new layer to overwrite the old layers of the same type, something like this
```r
autoplot(gs, popname) + stats_null() + geom_stats(type = "count")
```
This will require quite a bit work on our end since we do the lazy layer adding operation (i.e. `+` operator), which is different from `ggplot`.  So all the layers need to be recorded and processed in order at the end. We will have a group discussion to decide whether to bring this feature to ggcyto.

**Comment by mikejiang** [comment]
I've experimented the idea of `_null` layers which seems to work so far
```r
> dataDir <- system.file("extdata",package="flowWorkspaceData")
> gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))
> #autoplot display pop stats by default
> p <- autoplot(gs1, "CD4")
> p
```
![image](https://user-images.githubusercontent.com/1385649/79679123-f48b7580-81b7-11ea-8137-897ea93f7e86.png)
```r
> #it is easy to remove the default stats
> p <- p + stats_null()
> p
```
![image](https://user-images.githubusercontent.com/1385649/79679138-1684f800-81b8-11ea-9f1e-c788314f0487.png)

```r
> #and add a new one
> p <- p + geom_stats(type = "count")
> p
```
![image](https://user-images.githubusercontent.com/1385649/79679156-37e5e400-81b8-11ea-8b37-467577d88b4f.png)

Due to the upcoming bioc release, we are freezing `master` branch for now, this new feature currently is in `stats_null` branch, feel free to play with it and let us know if it works for you.

**Comment by mikejiang** [comment]
@PedroMilanezAlmeida  `gate_null()` is also added.

**Comment by PedroMilanezAlmeida** [comment]
That is pretty cool! I try and let you know!
